---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consolereconciler-additional-cluster-role
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      # The "create" verb cannot be used with "resourceNames"
      - leases
    verbs:
      - create

  - apiGroups:
      - coordination.k8s.io
    resources:
      # The cluster operator needs to access and manage leases for leader election
      - leases
    resourceNames:
      - console-operator-lease
    verbs:
      - get
      - list
      - watch
      - delete
      - patch
      - update
      # temporary until available: https://github.com/operator-framework/java-operator-sdk/pull/2456
      - create

  # Granted to Prometheus instances
  - apiGroups: [ '' ]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: [ get, list, watch ]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: [ get, list, watch ]
  - nonResourceURLs: [ /metrics ]
    verbs: [ get ]

  # Used directly by operator and granted to Console instances
  - verbs:
      - get
      - watch
      - list
    apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkatopics
      - kafkausers
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consolereconciler-additional-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: consolereconciler-additional-cluster-role
subjects:
  - kind: ServiceAccount
    name: console-operator
